const systemFiles = [
    {
        "id": "welcome",
        "systemFile": true,
        "name": ".docs/welcome",
        "content": [
            { "text": "Welcome to BlueBook", "tabs": { "full": 0 }, "decos": ["h1"] },
            { "text": "Your fast, minimal, keyboard-first note system.", "tabs": { "full": 0 }, "decos": ["subtitle"] },
            { "tabs": { "full": 0 } },
            { "text": "This document is always here when you log in – your built-in help page and reference sheet. The app – and with it this welcome message – is still under construction, so please take anything you read here with a grain of salt.", "tabs": { "full": 0 } },
            { "tabs": { "full": 0 } },
            { "text": "Why This Editor Is Different", "tabs": { "full": 0 }, "decos": ["h2"] },
            { "text": "• Snippets: typesetting equations is a breeze if you have the right tools.", "tabs": { "full": 0 } },
            { "text": "• No Markdown: what you type is what you get. No invisible syntax, no jumping cursors, no surprises.", "tabs": { "full": 0 } },
            { "text": "• Keyboard-first: every action has a hotkey. The mouse is completely optional.", "tabs": { "full": 0 } },
            { "text": "• Vim Mode: to make editing even faster. Highly recommended.", "tabs": { "full": 0 } },
            { "tabs": { "full": 0 } },
            { "text": "Math Support (MathJax)", "tabs": { "full": 0 }, "decos": ["h2"] },
            { "text": "Inline math looks like this: E^2=m^2c^4-p^2c^2.", "tabs": { "full": 0 }, "marks": [{ "role": "math", "from": 694, "to": 711 }] },
            { "tabs": { "full": 0 } },
            { "text": "Display math looks like this:", "tabs": { "full": 0 } },
            { "text": "i\\gamma^{\\mu}\\partial_{\\mu}\\psi-\\left(\\frac{mc}{\\hbar}\\right)\\psi=0", "tabs": { "full": 0 }, "decos": ["math"] },
            { "text": "Snippets make typing LaTeX fast: you can learn all about them in the Snippets section.  Some snippets also work outside math – e.g. turning => into ⇒.", "tabs": { "full": 0 } },
            { "tabs": { "full": 0 } },
            { "text": "Command Palette & File Picker", "tabs": { "full": 0 }, "decos": ["h2"] },
            { "text": "Open the command palette: <Command+p> or <Ctrl+Shift+p>", "tabs": { "full": 0 } },
            { "text": "Type anything — it fuzzy-finds commands instantly.", "tabs": { "full": 0 } },
            { "tabs": { "full": 0 } },
            { "text": "Open the file picker: <Command+o> or <Ctrl+Shift+o>", "tabs": { "full": 0 } },
            { "text": "• Fuzzy-find notes", "tabs": { "full": 0 } },
            { "text": "• Or create a new note by typing a name and pressing <Command+Enter> or <Ctrl+Enter>", "tabs": { "full": 0 } },
            { "tabs": { "full": 0 } },
            { "text": "Try creating a note called \"My first BlueBook note\".", "tabs": { "full": 0 } },
            { "tabs": { "full": 0 } },
            { "text": "Snippets", "tabs": { "full": 0 }, "decos": ["h2"] },
            { "text": "Customisation – coming soon", "tabs": { "full": 0 }, "decos": ["h3"] },
            { "text": "You can customize or add your own in:", "tabs": { "full": 0 } },
            { "text": "• .config/snippets", "tabs": { "full": 0 } },
            { "text": "• See defaults in: .default/snippets", "tabs": { "full": 0 } },
            { "tabs": { "full": 0 } },
            { "text": "Tabstops", "tabs": { "full": 0 }, "decos": ["h3"] },
            { "text": "Tabstops are predefined jump locations for your cursor in snippets. They can jump to empy spaces or highlight some default value. If the same variable appears multiple times, all appearances will be edited simultaneously. Move to the next tabstops with <Tab>.", "tabs": { "full": 0 } },
            { "tabs": { "full": 0 } },
            { "text": "Examples", "tabs": { "full": 0 }, "decos": ["h3"] },
            { "text": "• Typing inside inline math \"eex\" → expands to e^{ x }.", "tabs": { "full": 0 }, "marks": [{ "role": "math", "from": 1771, "to": 1778 }] },
            { "text": "• \"der\" in math will turn into \\frac{\\mathrm{d} y}{\\mathrm{d} x}. First the \"y\", then the \"x\" will be highlighted. If you press <Tab> again, you'll jump to the end of the expression.", "tabs": { "full": 0 }, "marks": [{ "role": "math", "from": 1811, "to": 1844 }] },
            { "text": "• You can type greek letters by \";\" and their latin equivalents: \";a\" → \\alpha.", "tabs": { "full": 0 }, "marks": [{ "role": "math", "from": 2035, "to": 2041 }] },
            { "text": "• If you type \"hat\" after a latin or greek letter, it will wrap the letter accordingly: \"ahat\" → \\hat{a}.", "tabs": { "full": 0 }, "marks": [{ "role": "math", "from": 2140, "to": 2147 }] },
            { "text": "• Typing \"3mat\" will give you a 3x3 matrix: \"3mat\" →", "tabs": { "full": 0 } },
            { "text": "\\begin{bmatrix} 0 & 0 & 0 \\\\ 0 & 0 & 0 \\\\ 0 & 0 & 0 \\end{bmatrix} .", "tabs": { "full": 0 }, "decos": ["math"] },
            { "tabs": { "full": 0 } },
            { "text": "Personal Configuration – coming soon", "tabs": { "full": 0 }, "decos": ["h2"] },
            { "text": "All user-configurable files are just normal notes stored in:", "tabs": { "full": 0 } },
            { "text": "• .config/ — Your personal config", "tabs": { "full": 0 } },
            { "text": "• .default/ — The app’s shipped defaults", "tabs": { "full": 0 } },
            { "tabs": { "full": 0 } },
            { "text": "Open them like any other file. The editor doesn’t treat them specially — no magic, no formats to learn.", "tabs": { "full": 0 } },
            { "tabs": { "full": 0 } },
            { "text": "Common config files:", "tabs": { "full": 0 } },
            { "text": "• .config/hotkeys — your hotkeys", "tabs": { "full": 0 } },
            { "text": "• .config/theme — theme & colors", "tabs": { "full": 0 } },
            { "text": "• .config/snippets — snippets", "tabs": { "full": 0 } },
            { "text": "• .config/settings — general settings", "tabs": { "full": 0 } },
            { "tabs": { "full": 0 } },
            { "text": "You can edit them freely.", "tabs": { "full": 0 } },
            { "text": "If you break something, open the corresponding file in .default and copy it back.", "tabs": { "full": 0 } },
            { "tabs": { "full": 0 } },
            { "text": "Useful Hotkeys and Snippets", "tabs": { "full": 0 }, "decos": ["h2"] },
            { "text": "The <Meta> key is <Command> on Mac and <Ctrl> on Windows machines. Some hotkeys also work with <Shift> if, the <Shift>-less version clashes with something on your OS.", "tabs": { "full": 0 } },
            { "tabs": { "full": 0 } },
            { "text": "• Search notes: <Meta+o>", "tabs": { "full": 0 } },
            { "text": "• Command palette: <Meta+p>", "tabs": { "full": 0 } },
            { "text": "• Save file: <Meta+s>", "tabs": { "full": 0 } },
            { "text": "• Toggle bold on a selection: <Meta+b>", "tabs": { "full": 0 } },
            { "text": "• Toggle bold on a line: <Meta+Shift+b>", "tabs": { "full": 0 } },
            { "text": "• Heading 1: <Meta+Shift+a> or h1", "tabs": { "full": 0 } },
            { "text": "• Heading 2: <Meta+Shift+s> or h2", "tabs": { "full": 0 } },
            { "text": "• Heading 3: <Meta+Shift+d> or h3", "tabs": { "full": 0 } },
            { "text": "• Heading 4: <Meta+Shift+f> or h4", "tabs": { "full": 0 } },
            { "text": "• Remove line decorations: h0", "tabs": { "full": 0 } },
            { "text": "• Toggle display math: <Meta+Shift+m> or <Meta+d>", "tabs": { "full": 0 } },
            { "text": "• Toggle inline math: <Meta+m>", "tabs": { "full": 0 } },
            { "text": "• New note: <Meta+Enter> in the File Picker", "tabs": { "full": 0 } },
            { "tabs": { "full": 0 } },
            { "text": "Quick Demo Area", "tabs": { "full": 0 }, "decos": ["h2"] },
            { "text": "Try things out here:", "tabs": { "full": 0 } },
            { "text": "• Make this line bold", "tabs": { "full": 0 } },
            { "text": "• Make this a heading", "tabs": { "full": 0 } },
            { "text": "• Add some inline math: add the Pyhtagorean theorem here", "tabs": { "full": 0 } },
            { "text": "• Add display math to the next line: type in Maxwell's equations", "tabs": { "full": 0 } },
            { "tabs": { "full": 0 } },
            { "text": "• Trigger a snippet: writing paratheses is faster with ;j", "tabs": { "full": 0 } },
            { "text": "• Open the file picker and create a file named \"testing features\"", "tabs": { "full": 0 } },
            { "tabs": { "full": 0 } },
            { "text": "Have Fun", "tabs": { "full": 0 }, "decos": ["h2"] },
            { "text": "This app is built to be fast, predictable, and delightful with the keyboard.", "tabs": { "full": 0 } },
            { "text": "Customize everything. Experiment. Break things, fix them. Make it yours", "tabs": { "full": 0 } }
        ],
    }
]

export default systemFiles;
